name: Semantic Release
on:
  push:
    branches:
      - main
      - alpha
      - beta
jobs:
  semantic-release-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # this is needed because: https://github.com/semantic-release/github/issues/175#issuecomment-1122569317
          token: ${{ secrets.GH_TOKEN }}
      - run: npm install
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19.0.2
          branches: |
            [
              'main',
              {
                name: 'beta', 
                prerelease: true
              }, 
              {
                name: 'alpha', 
                prerelease: true
              }
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_NPM_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_NPM_CONFIG_REGISTRY: https://npm.pkg.github.com/
          PUBLIC_NPM_CONFIG_REGISTRY: https://registry.npmjs.org
